dynatrace-oss/dynatrace-gcp-monitor

README.md, dockerfile, k8s/dynatrace-gcp-function.yaml, src/lib/credentials.py
=> docker docs + yaml objects definition

HACKING.md, src/lib/context.py, src/lib/metric_ingest.py, src/main.py
Introduce option to disable SSL cerificate verification on push to Dynatrace
=> Introduce option to disable SSL verification

HACKING.md, src/lib/context.py, src/lib/metric_ingest.py, src/main.py
Please check if the implementation is sound. If so, I'll add documentation and tests (if possible)
=> APM-272389 fix RATE_LIMIT_EXCEEDED problem

src/config/k8s_container.yml, src/lib/metric_ingest.py
Minor fixes for issues with a couple metrics reported in #50
=> APM-290594: Minor fixes for metrics regarding the issue #50

src/config_logs/cloud_function.json, tests/unit/extraction_rules/test_cloud_function.py
Extended GCP cloud function config. Added faas.name and extended content source fields.
=> [APM-292700] Extended gcp cloud function config

src/config_logs/common.json, src/lib/logs/metadata_engine.py
the name of this attribute has recently changed in Dynatrace
=> change dt.logpath to log.source

HACKING.md, activation-config.yaml, scripts/setup.sh
=> APM-3013689: Added validation of parameters from activation-config.yaml

README.md
- Added link to Azure monitoring
=> APM-306505 Cleanup gcp-function GitHub documentation

src/lib/configure_dynatrace.py, src/lib/logs/log_forwarder.py
I've missed duplicated dashboard import in Python in the first PR, fixing it now. Additionally I've found out that when SA doesn't have permission to fetch Pub/Sub messages, it will continue to try, spamming logs and sending requests which are bound to fail. I've added 60 second backoff in case of Google API Forbidden Exception.
=> APM-307428: fix dashboard import for k8s & little error handling fix

scripts/setup.sh, scripts/uninstall.sh, scripts/update.sh
- updated yq syntax to match 4+ version
- added check for version
=> [APM-313066] -Upgrade yq syntax in setup.sh script

scripts/setup.sh
- validate queryInterval values range
- recreate Cloud Scheduler every time (it must be recreated when queryInterval changes)
- fix Cloud Function installs parameters validation
=> queryInterval parameter validation

k8s/helm-chart/dynatrace-gcp-function/values.yaml, scripts/deploy-helm.sh
Tested using a public AG:
```
deploymentType: "logs"
dynatraceUrl: ""
dynatraceLogIngestUrl: "htts://jxw01498.dev.dynatracelabs.com/"
activeGate.useExisting: "true"
activeGate.dynatracePaasToken: ""
requireValidCertificate: "true"
```
with a Function generating a specific log every minute:
It works!
=> APM-321122 allow log ingest through Public AG

k8s/helm-chart/dynatrace-gcp-function/values.yaml, scripts/deploy-helm.sh
Rolling back the Public AG changes until's ready.
=> rollback Public AG

src/lib/context.py, src/lib/entities/extractors/cloud_function.py, src/lib/entities/extractors/cloud_sql.py, src/lib/entities/extractors/filestore_instance.py, src/lib/entities/extractors/gce_instance.py, src/lib/entities/extractors/pubsub_subscription.py, src/lib/entities/google_api.py, src/lib/metric_ingest.py
SERVICE_USAGE_BOOKING setting was not respected by infrastructure calls. Common method has been extracted to avoid similar bugs in future. I'm waiting for new GCP project setup for full manual test
=> APM-327948: Respect SERVICE_USAGE_BOOKING on infrastructure API calls

build/docker-deploy.sh
Current update of version file was not working at all, logs generated from running K8S deployment were:
_2021-10-21 14:57:50.841112  : Found version: dev_
=> Fix writing version file

src/lib/clientsession_provider.py, src/lib/extensions_fetcher.py, src/lib/fast_check.py, src/lib/instance_metadata.py, tests/e2e/sample_app/main.py, tests/unit/metrics_ingest_test.py, tests/unit/test_extension_fetcher.py, tests/unit/test_fast_check.py, tests/unit/test_self_monitoring.py
Added lacking license info to files
=> Added license info to files

src/lib/clientsession_provider.py, src/lib/configure_dynatrace.py, src/lib/fast_check.py, src/lib/gcp_apis.py, src/lib/instance_metadata.py, src/lib/logs/log_forwarder_variables.py, src/lib/logs/log_sfm_metrics.py, tests/e2e/sample_app/main.py, tests/integration/logs/__init__.py, tests/unit/metrics_ingest_test.py, tests/unit/test_fast_check.py, tests/unit/test_self_monitoring.py
Added lacking license info to files
=> Added license info to files - master

scripts/setup.sh
Fixed Verify link due to changes in documentation.
=> Fixed Verify link

activation-config.yaml, scripts/deploy-function.sh, scripts/lib.sh, scripts/setup.sh, tests/e2e/deployment-test-cloud-function.sh
Needs to be synced with doc change
=> APM-340237: GCP Function - remove interactive params

scripts/uninstall.sh
Build error related to APM-355118
=> APM-354663 uninstall should use activation config

scripts/deploy-helm.sh
During installation of autopilot cluster, check if the GKE API needs to be enabled
=> APM-357141 Enable GKE API if it is not enabled

scripts/deploy-helm.sh, scripts/lib.sh
Changed the limit of repetition count to {1,255} in a regex for checking URL in deploying script
=> APM-345053 Changed the limit of repetition count to {1,255} 

k8s/helm-chart/dynatrace-gcp-function/values.yaml, scripts/deploy-helm.sh
Added vpcNetwork param to values.yaml, with default value, so the customer can select in which network to deploy the autopilot cluster
=> Added vpcNetwork parameter

src/lib/credentials.py, tests/integration/metrics/mappings/v1_projects-f67c0a4d-0456-4d4f-aa32-4288a2167256.json
This change has been made for testing purposes only. It will be reverted back.
=> PCLOUDS-1263 Set pageSize attribute to one for testing purposes

src/lib/credentials.py, tests/integration/metrics/mappings/v1_projects-f67c0a4d-0456-4d4f-aa32-4288a2167256.json
Reverting the changes after tested successfully
=> PCLOUDS-1263 Reverted previously made changes

.travis.yml
https://docs.travis-ci.com/user/notifications/
=> Send email notification when build on master fails

src/lib/webserver/webserver.py, src/run_docker.py
New thread with new loop for webserver, for both Metrics and Logs modes
=> PCLOUDS-1623-LivenessProbe_failing

src/lib/metric_ingest.py
Main change is verifying the 'offset' and 'width' values from datapoints for linear type metrics.
=> PCLOUDS-1598: Verify offset and width values for linear metric type

k8s/helm-chart/dynatrace-gcp-function/values.yaml
Feature set in extension: https://bitbucket.lab.dynatrace.org/projects/DEXT2/repos/google-sql/browse/src/extension/extension.yaml#744
=> Add Cloud SQL feature set to values.yaml

.travis.yml, tests/e2e/metrics/test_metrics.py
=> - Fixed Github Releases

HACKING.md, k8s/helm-chart/dynatrace-gcp-monitor/templates/function-config.yaml, k8s/helm-chart/dynatrace-gcp-monitor/templates/function-deployment.yml, k8s/helm-chart/dynatrace-gcp-monitor/values.yaml, src/dev_local_run.py, src/lib/clientsession_provider.py, src/lib/configuration/config.py, src/lib/context.py, src/lib/credentials.py, src/lib/dt_extensions/extensions_fetcher.py, src/lib/fast_check.py, src/lib/instance_metadata.py, src/lib/logs/dynatrace_client.py, src/lib/logs/log_forwarder.py, src/lib/logs/log_forwarder_variables.py, src/lib/logs/log_self_monitoring.py, src/lib/logs/logs_processor.py, src/lib/metric_ingest.py, src/lib/utilities.py, src/lib/webserver/webserver.py, src/main.py, src/requirements.txt, src/run_docker.py, tests/e2e/lib-tests.sh, tests/integration/logs/test_integration.py
Most of it is cleaning code, renaming and small refactors. Main fixes are:
- Fixed endpoint for instance metadate check.
- Refactor in SFM loop creation.
- Increasing of default resources.
- Update of pubsub library version, because it was marked as problematic.
- Resetting of k8s env vars when running perf tests, because it was affecting subsequent e2e test runs.
=> PCLOUDS-2824: Cleaning and fixing small issues with build

src/config_logs/google-sql/cloud_sql.json, src/lib/logs/jmespath.py
Fix problem with log being written in CAPITAL LETERS
=> NOISSUE-fix-cloud_sql-region

k8s/helm-chart/dynatrace-gcp-monitor/values.yaml, scripts/deploy-helm.sh
Adding new parameters:
--cluster-ipv4-cidr,  
--services-ipv4-cidr,
--master-ipv4-cidr
=> PCLOUDS-1862: Add CIDR param for cluster in GCP Monitor deployment script

src/lib/metric_ingest.py
There are a couple of metrics, like:
- container/cpu/utilizations
- container/memory/utilizations
from Cloud Run, which are defined as: `DELTA, DISTRIBUTION, 10^2.%`. In some cases, we were not multiplying their values (we receive 100 times smaller values -that is something Google does whenever the unit is 10^2.%-). So, the fix addresses those cases.
See in GCP, for example, that values vary around 9%:
In DT, we see before (0.09%) and after the fix (correct ~9%):
=> PCLOUDS-5327: Fixed datapoints values for distribution types

k8s/helm-chart/dynatrace-gcp-monitor/values.yaml, scripts/lib.sh
- Small updates to yq jq test error messages as they appeared to be misleading to some users (see DAQ-4833)
- Remove misleading comment.
=> Update some error messages and comment

.travis.yml
Travis CI deploy - migrate to dpl v2
=> Travis CI deploy - migrate to dpl v2
