dynatrace-oss/dynatrace-gcp-monitor

src/lib/credentials.py
src/main.py

This PR Improves log message on issues with default authorization, example:
````
Starting execution [2020-10-06T09:06:39.241935]
Trying to use default service account
Failed to authorize with Service Account from Metadata Service due to 'Cannot connect to host metadata.google.internal:80 ssl:default [getaddrinfo failed]'
Cannot proceed without authorization token, stopping the execution
Execution [2020-10-06T09:06:39.241935] took 1.2832658290863037
````

Print accessible info on missing service account or metadata service unavailable

---

src/lib/context.py
src/lib/credentials.py
src/lib/entities/decorator.py
src/lib/entities/extractors/cloud_function.py
src/lib/entities/extractors/cloud_sql.py
src/lib/entities/extractors/filestore_instance.py
src/lib/entities/extractors/gce_instance.py
src/lib/entities/extractors/pubsub_subscription.py
src/lib/entities/google_api.py
src/lib/metric_ingest.py
src/lib/self_monitoring.py
src/main.py
src/run_docker.py

Log messages are prefixed with UTC ISO datetime string and execution identifier in `[]`. Example output: 
````
,,,,,..
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,.
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
.,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,     ,,
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,    .,,,,
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,     ,,,,,,,.
.,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,.    ,,,,,,,,,,,
,,,,,,,,,,,,,,,,,......  ......,,,,,,,    .,,,,,,,,,,,,,
,,                                        ,,,,,,,,,,,,,,,,
,,,,,,,,,,,,,,,,,                        .,,,,,,,,,,,,,,,,
,,,,,,,,,,,,,,,,,                        .,,,,,,,,,,,,,,,,.
,,,,,,,,,,,,,,,,,       Dynatrace        .,,,,,,,,,,,,,,,,.
,,,,,,,,,,,,,,,,, dynatrace-gcp-function .,,,,,,,,,,,,,,,,,
,,,,,,,,,,,,,,,,, …
```

Improve logging for k8s deployments

---

scripts/setup.sh
src/lib/metric_ingest.py

Fix to support URL's in Dynatrace managed format: https://abcd.managed-dt.dynalabs.io/e/ett29184-1ae2-46dd-96fe-02957773fc57/ 
Using urljoin removes all URL segments .. :(

fix for dynatrace manged urls

---

generate_ddu_estimation.py

Output is a JIRA markdown table:
````
|| name || data points rate (/min) || estimated DDU rate (/min) (1 data point = 0.001 DDU)||
| api | 86.0 | 0.086 |
| cloudsql_database | 66.0 | 0.066 |
| cloud_function | 73.0 | 0.073 |
| datastore_request | 24.0 | 0.024 |
| filestore_instance | 48.0 | 0.048 |
| gce_instance | 2287332170205.0 | 2287332170.205 |
| gcs_bucket | 185.0 | 0.185 |
| https_lb_rule | 3897.0 | 3.897 |
| internal_http_lb_rule | 405.0 | 0.405 |
| internal_tcp_lb_rule | 135.0 | 0.135 |
| internal_udp_lb_rule | 108.0 | 0.108 |
| tcp_lb_rule | 45.0 | 0.045 |
| udp_lb_rule | 36.0 | 0.036 |
| pubsub_snapshot | 21.0 | 0.021 |
| pubsub_subscription | 166.0 | 0.166 |
| pubsub_topic | 49.0 | 0.049 |
| pubsublite_topic_partition | 10.0 | 0.01 |
````
Estimation for `gce_instance` is …

APM-264620: DDU estimation script

---

src/lib/context.py
src/lib/fast_check.py
src/lib/metric_ingest.py
src/lib/self_monitoring.py
src/main.py

Changes:
- Configuration flags are printed on the startup
- Additional log messages have been added on service booking check, to improve visibility of what kind of booking is used
- `SERVICE_USAGE_BOOKING` value is sanitized before checking for equality with `destination` to avoid any mismatches with leading whitespaces etc.
- FastCheck check for Dynatrace connectivity was performed for each configured project, which makes no sense as function uses single set of credentials. Now it is performed once.
- Printing out SFM data has been added as most users are not permitting the function to create SFM metrics.
- `gcp_metric_request_count` is not sent to GCP Monitor metrics yet - that requires deeper consideration of dimensions and documentation update, I've decided it is out of scope of this …

APM-290460: Logging improvements and SERVICE_USAGE_BOOKING flag sanitization

---

.travis.yml
HACKING.md
src/lib/context.py
src/lib/credentials.py
src/lib/entities/decorator.py
src/lib/entities/extractors/cloud_function.py
src/lib/entities/extractors/cloud_sql.py
src/lib/entities/extractors/filestore_instance.py
src/lib/entities/extractors/gce_instance.py
src/lib/entities/extractors/pubsub_subscription.py
src/lib/entities/google_api.py
src/lib/entities/model.py
src/lib/logs/__init__.py
src/lib/logs/dynatrace_client.py
src/lib/logs/log_forwarder.py
src/lib/logs/logs_processor.py
src/lib/logs/logs_sending_worker.py
src/lib/metric_ingest.py
src/lib/self_monitoring.py
src/main.py
src/operation_mode.py
src/requirements.txt
src/run_docker.py
tests/__init__.py
tests/integration/test_integration.py
tests/requirements.txt

Initial POC of log forwarder in container. `dynatrace_client` has been copied from Azure log forwarder solution. Job queue and Pub/sub subscriber parameters have been selected arbitrarily, we need to run performance tests to fine tune them. Default behavior of `run_docker` scripts has been preserved.
I've introduced simple integration test with wiremock, as it happened to be simpler than messing with mocks. New stage has been added to `.travis.yml` to run the tests.

APM-292194: Run Logs POC in container

---

src/lib/context.py
src/lib/fast_check.py
src/lib/instance_metadata.py
src/lib/logs/dynatrace_client.py
src/lib/logs/log_forwarder.py
src/lib/logs/logs_sending_worker.py
src/run_docker.py
tests/integration/test_integration.py

Introduced `LogsFastCheck` which prints out version and configuration flags for logs forwarder. Additionally it sends startup message to configured log ingest endpoint - which is verification of configuration and acts as a diagnostic information.
Additional changes:
- fix for outdated timestamps in integration test - test was passing but all messages were stashed due to too old timestamp
- Preserve asyncio loop in daemon thread to keep aiohttp working for logs forwarding

APM-293893: Implement FastCheck for Logs

---

.travis.yml
HACKING.md
src/config_logs/cloud_function.json
src/config_logs/common.json
src/config_logs/default.json
src/lib/context.py
src/lib/logs/dynatrace_client.py
src/lib/logs/jmespath.py
src/lib/logs/log_forwarder.py
src/lib/logs/logs_processor.py
src/lib/logs/logs_sending_worker.py
src/lib/logs/metadata_engine.py
src/requirements.txt
tests/integration/test_integration.py
tests/unit/extraction_rules/test_cloud_function.py
tests/unit/extraction_rules/test_default.py
tests/unit/test_metadata_engine.py

This PR introduces Metadata Engine for GCP Logs Forwarder. Engine is the same as in Azure Logs Forwarder, with small tweak - `common.json` configuration has been introduced. This ruleset is evaluated before any other rules. This is meant to address the fact that GCP log message is well defined and structured, so without we would have a lot of duplicated rules across configurations. Simple config for Cloud Function has been introduced only as a proof that rules are correctly evaluated.
When developing I came across weird issue with full internal message queue, I wasn't able to reproduce it, but I suspect that due to my internet connection issues, requests to Dynatrace were timing out. To mitigate it in future, I've introduced a couple small tweaks:
- defined 30 second timeout for requests …

Initial Metadata extraction for GCP Logs Forwarder

---

HACKING.md
activation-config.yaml
k8s/helm-chart/dynatrace-gcp-function/templates/template.yml
src/lib/credentials.py
src/lib/logs/logs_sending_worker.py
tests/integration/test_integration.py

Added possibility to use sepatate endpoint for metrics (MINT API on cluster server) and logs (Generic Logs Ingest API on ActiveGate node)

[APM-293900] support separate config entry for logs ingest Dynatrace endpoint

---

src/lib/metric_ingest.py
src/main.py

Some of dimension values may have different type than `str`, which triggers error on `len()` call. I've added error logging clause on `process_project_metrics`, because before it could swallow errors quietly.

Fix len() Exception when limiting dimension value size

---

k8s/dynatrace-gcp-function.yaml

GCP Function HTTPS_PROXY and HTTP_PROXY environment variables are defined in config map

GCP Function HTTPS_PROXY and HTTP_PROXY environment variables are defined in config map

---

src/lib/configure_dynatrace.py
src/lib/fast_check.py

I've searched through codebase to check if there are any other calls to Dynatrace API without applying the flag, but I've found none.

APM-304323: Correctly apply REQUIRE_VALID_CERIFICATE to API calls from run_docker init

---

src/config_logs/cloud_audit_logs.json
src/config_logs/common.json
src/lib/logs/jmespath.py
src/lib/logs/metadata_engine.py
tests/unit/extraction_rules/test_audit_activity.py
tests/unit/extraction_rules/test_audit_data_access.py
tests/unit/extraction_rules/test_audit_policy.py
tests/unit/extraction_rules/test_audit_system_event.py
tests/unit/extraction_rules/test_cloud_function.py

Minor change to metadata engine itself - discussion with @pawelsiwek lead to conclusion we should apply `audit_logs` rules to logs matched with other rules, and apply them last, to overwrite any attributes introduced by other rules.

APM-292701: Mapping Audit Logs

---

k8s/helm-chart/dynatrace-gcp-function/templates/template.yml
k8s/helm-chart/dynatrace-gcp-function/values.yaml

Not introducing this value as `deploy-helm.sh` parameter, as with APM-306738 user will edit `values.yaml` directly

APM-306494: Docker image param for Helm chart

---

src/lib/entities/extractors/cloud_function.py
src/lib/entities/extractors/cloud_sql.py
src/lib/entities/extractors/filestore_instance.py
src/lib/entities/extractors/gce_instance.py
src/lib/entities/extractors/pubsub_subscription.py
src/lib/entities/model.py
src/lib/metric_ingest.py
src/main.py
tests/e2e/deployment-test.sh
tests/unit/metrics_ingest_test.py

After discussion with @pawelsiwek and @sq2gxo we came to conclusion that we should entirely drop adding "indexed" dimension values for dimensions extracted from entities.
Additionally, I've doubled number of helm deployment status check periods in E2E test, as it caused the test to be flaky.

Stop adding multiple values with indexes for entity dimensions

---

scripts/setup.sh

after fix
```
...
- create self monitoring dashboard
Dashboard already exists, skipping
- Dashboard [Google Cloud APIs] already exists on cluster, skipping
- Dashboard [Google Cloud Function] already exists on cluster, skipping
- Dashboard [Google Cloud SQL] already exists on cluster, skipping
- Dashboard [Google Cloud Datastore] already exists on cluster, skipping
- Dashboard [Google Cloud Storage] already exists on cluster, skipping
- Dashboard [Google Cloud HTTPs Load Balancing] already exists on cluster, skipping
- Dashboard [Google Kubernetes Engine] already exists on cluster, skipping
- Dashboard [Google Cloud Pub/Sub] already exists on cluster, skipping
- Dashboard [Google Cloud Pub/Sub] already exists on cluster, skipping
- Dashboard [Google Cloud TCP Load Balancing] already …
```

APM-318373 fix parsing yq bug

---

src/lib/credentials.py
src/main.py
tests/integration/logs/test_integration.py
tests/integration/metrics/test_integration_metric.py

- [k8s installation] project_id is taken now from environment variable GCP_PROJECT or in case it's not available(tests) a default "dynatrace-gcp-extension" value is used
- added documentation.

[APM-326992] GCP- project env

---

scripts/lib.sh
scripts/setup.sh
src/lib/extensions_fetcher.py
src/lib/utilities.py
tests/e2e/extensions/test_types.py
tests/unit/test_activation_config.py
tests/unit/test_extension_fetcher.py

Fixes:
- filtering for k8s deployment
- do not upload extensions which are already uploaded to the cluster (setup.sh)
- not required last '/' in cluster url (setup.sh)

Extensions fixes

---

tests/e2e/metrics/test_metrics.py

Ok, so I just spent some time trying to fetch metric value from GCP to compare it to value we sent to Dynatrace and it seems more complicated than I thought, have issues to get it running.
Reason to do this is that we have test function in GCP that we call exactly 5 times, but its execution_count metric in GCP is sometimes 6 or 7 (this behavior started 18.02.2022). 
This PR (don't check for specific value 5/6/7, just check if there is some value) is not a perfect solution but it does still test the fact that metric IS sent to Dynatrace. Just the value isn't checked anymore.
Given current situation multiple tickets and release is blocked I think we should go with this and then maybe prepare some higher quality solution. What do you think??

APM-355118: Temporary E2E test

---

scripts/deploy-helm.sh

The issue lied in piping commands into tee - if the piped commanded exited with non-zero status, the trap wasn't triggered.
Setting the pipefail shell option fixes the issue. 
Without setting pipefail:
With pipefail:

Fail fast on deployment errors in GCP k8s

---

scripts/deploy-helm.sh

Having compute/zone set in a command line tool lead to `gcloud container cluster` calls to automatically append a `--zone` parameter, which leads to an error when creating autopilot cluster: 
Autopilot clusters have to be regional, but for some reason allow passing `--zone` .
Passing empty zone parameters fixes this issue.

add empty zone parameter to gcloud container calls

---

.travis.yml

e2e-helm-deployment-test stage uses artifacts in a GCP bucket which are created in the build stage. 
However, the build stage is only triggered by non-release builds causing release builds to fail on the test stage. 
Removing the 'if' should fix the issue.

build stage now triggers on release builds

---

scripts/lib.sh

I only changed the default URL and added a comment to indicate that the file is accessed through Cloudfront.
All the variables names referencing a S3 bucket remain the same, as well as the argument name that the customer can use to select the file location during installation.

Changed S3 to Cloudfront URL

---

scripts/deploy-helm.sh

For the autopilot cluster deployment, this property is already true by default, so I am only setting it in case it is not defined at the beginning of the setup script.
If the property is set to false, the new AG is created in k8s, so for the cloud function deployment, there's no option, it always uses an existing AG.

Existing AG property to true by default

---

HACKING.md
src/lib/context.py

Increase the default of metric lines ingested due to relaxing limits on the metric ingest API.

Increase maximum metric data points per minute

---

scripts/deploy-helm.sh
src/lib/fast_check.py

Changes:
- Set USE_EXISTING_ACTIVE_GATE to true by default before readonly statement.
- DYNATRACE_URL validations in every case, since it's now required.
- LOG_VIEWER URL for every case in which logs are ingested, since DYNATRACE_URL is now required.
- Log record indicating invalid token permissions is now displayed only in case the token was retrieved successfully but has incorrect scopes (or is revoked). Before this, if a network/communication error happened in the token call, the token_metadata variable was returned as an empty dict ({}) and this log was also displayed, which was misleading.
- Remove occurrences of whitespaces, \r, \n & \t in error prone parameters

Fix conditions of parameters validations and condition of invalid token permissions

---

HACKING.md
MIGRATION-V1.md
README.md

Fixing links to Dynatrace documentation in markdown files.
Marking Cloud Function deployment as deprecated in MIGRATION-V1.md
Removing info about reusing Dynatrace API token in MIGRATION-V1.md

PCLOUDS-1519 - fixing dead links in README

---

dockerfile
src/requirements.txt

- The latest version of aiohttps doesn't contain an examples folder with a secret key: /usr/local/lib/python3.8/site-packages/examples/server.key
- gcp monitor is now running under the gcp-monitor user, not root(as it was prev)

Pclouds 2240 change docker user

---

k8s/helm-chart/dynatrace-gcp-monitor/templates/function-config.yaml
k8s/helm-chart/dynatrace-gcp-monitor/templates/function-deployment.yml
k8s/helm-chart/dynatrace-gcp-monitor/values.yaml
src/lib/configuration/config.py
src/main.py

In addition to the full project_id filter, now this is able to filter by string contained into the project_id. Useful when yo have your GCP envs named with certain maner such as <provider>-<env>-<project>-<random-id> and you have one Dynatrace cluster for each env/proj/***

feat: added excluded_projects_by_prefix/substring capability

---

k8s/helm-chart/dynatrace-gcp-monitor/templates/function-config.yaml
k8s/helm-chart/dynatrace-gcp-monitor/templates/function-deployment.yml
k8s/helm-chart/dynatrace-gcp-monitor/values.yaml
src/lib/configuration/config.py
src/main.py

* feat: added excluded_projects_by_prefix function for env collecting
* feat: added excluded_projects_by_prefix capability
In addition to the full project_id filter, now this is able to filter by string contained into the project_id. Useful when yo have your GCP envs named with certain maner such as <provider>-<env>-<project>-<random-id> and you have one Dynatrace cluster for each env/proj/***
* feat: added excluded_projects_by_prefix/substring capability
* feat: added excluded_projects_by_prefix/substring capability
* feat: added excluded_projects_by_prefix/substring capability

feat: added excluded_projects_by_prefix/substring capability (#436)

---

.travis.yml
src/requirements.txt
tests/e2e/deployment-test-cleanup.sh
tests/e2e/deployment-test.sh
tests/e2e/execute-tests.sh
tests/e2e/lib-tests.sh
tests/e2e/sample_app/main.py
tests/requirements.txt

- Dependencies updates
- Adding sleep between creation of resources and E2E tests running (some resources need time to work properly)
- Running E2E tests only on master and on PRs (skipping pushes to dev branches)

NOISSUE: Small updates in e2e tests and dependencies

---

k8s/helm-chart/dynatrace-gcp-monitor/values.yaml
scripts/deploy-helm.sh
scripts/lib.sh

Add an option to use the VPCs created with custom subnets for cluster creation.
More context: when creating a VPC network the default option is creating custom subnets in this network,
then when this network is passed in the `values.yaml`, creating an autopilot cluster would fail because no subnet was specified.
Now it's possible to use VPC networks with both automatic and custom subnets.
Additionally, added some small cleaning, mainly breaking too long lines and fixing small inconsistencies.

Bugfix - allow for using VPC networks with custom subnet creation

---

src/config_logs/google-alloydb/alloydb_database.json
src/config_logs/google-alloydb/alloydb_instance.json

I have to use a logName instead of a resource container because in the second one, google provides project number instead of a project name ID
I don't know if this is a mistake or a deliberate action but this is the easiest solution to circumvent this problem

PCLOUDS-3941 add log schema alloydb

---

k8s/helm-chart/dynatrace-gcp-monitor/templates/function-config.yaml
k8s/helm-chart/dynatrace-gcp-monitor/templates/function-deployment.yml
k8s/helm-chart/dynatrace-gcp-monitor/values.yaml
src/lib/configuration/config.py
src/main.py

A copy of the community pull request: https://github.com/dynatrace-oss/dynatrace-gcp-monitor/pull/543
A Dynatrace developer responsible for this repository copied and pushed changes to allow the builds to pass. @ajth13 was consulted on the copy and creation of this PR. Thank you once again for your input in the dynatrace-gcp-monitor development. 
Original PR description:
> Where you can currently only exclude projects from monitoring this change adds the ability to specify a list to include.
> Business Justification
> 
> Enterprise customers with a large number of Dynatrace tenants and wants to be able to easily control which metrics are sent to which tenant and include list is much smaller than excluding all projects from other Dynatrace tenants.
> 
> Considerations
> 
> The project must …

[DAQ-4166] Added option to include projects

---

.travis.yml
Dockerfile
HACKING.md
requirements-dev.txt
src/lib/instance_metadata.py
src/requirements.txt
src/run_docker.py
tests/requirements.txt

- updated runtime and build environment to Python 3.12 (python 3.8 is end-of-life https://devguide.python.org/versions/)
- updated dependencies to latest versions containing latest security fixes

DAQ-7853 bump dependencies and python version
